news_website/main/routes.py
from flask import Blueprint, render_template

main = Blueprint("main", __name__)


@main.route('/')
@main.route('/home')
def home_page():
    return render_template('home.html')

news_website/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort
from flask_login import current_user, login_required, login_user, logout_user
from news_website import db, bcrypt
from news_website.users.forms import LoginForm, RegistrationForm, PasswordResetForm, ResetPasswordForm
from news_website.models import User, userType
from news_website.users.utils import send_reset_email

users = Blueprint("users", __name__)


@users.route('/login', methods=['GET', 'POST'])
def login_page():
    if current_user.is_authenticated:
        return redirect(url_for('main.home_page'))
    form = LoginForm()
    if form.validate_on_submit():
        # user = User.query.filter_by(email=form.email.data).first()
        # if user and (user.password == form.password.data):
        #     login_user(user)
        #     flash("Login Successful", 'success')
        #     return redirect(url_for('users.profile_page', user_id=current_user.id))
        # else:
        #     flash('Invalid email or password', 'danger')
        #     return redirect(url_for('users.login_page'))
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                flash('Login Successful', 'success')
                return redirect(url_for('main.home_page'))
            else:
                flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', form=form)


@users.route('/register', methods=['GET', 'POST'])
def registration_page():
    if current_user.is_authenticated:
        return redirect(url_for('main.home_page'))
    form = RegistrationForm()
    if form.validate_on_submit():
        ut = userType.query.filter_by(type=form.user_type.data).first()
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(user_type_id=ut.user_type_id, fname=form.fname.data, lname=form.lname.data, gender=form.gender.data,
                    email=form.email.data, phone=form.phone.data, age=form.age.data, address=form.address.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! Now you can login to your account', 'success')
        return redirect(url_for('users.login_page'))
    return render_template('registration.html', form=form)


@login_required
@users.route('/profile/<int:user_id>')
def profile_page(user_id):
    if user_id == current_user.id:
        typeOfUser = userType.query.filter_by(user_type_id=current_user.user_type_id).first()
        return render_template('profile.html', typeOfUser=typeOfUser)
    else:
        abort(403)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home_page'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to your id please check it to reset your password.', 'info')
        return redirect(url_for('users.login_page'))
    return render_template('reset_password_request.html', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home_page'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You can now log in', 'success')
        return redirect(url_for('users.login_page'))
    return render_template('reset_token.html', form=form)

news_website/templates/home.html
{% extends 'layout.html' %}
{% block content %}
<h1>This is home page.</h1>
{% endblock content %}

news_website/templates/layout.html
{#<!Doctype HTML>#}
{#<html>#}
{#    <!-- Required meta tags -->#}
{#    <meta charset="utf-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}
{##}
{#        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">#}
{#        <div class="navbar navbar-inverse">#}
{#            <div class="container-fluid">#}
{#                <div class="row">#}
{#                    <div class="col-md-12">#}
{##}
{#                        <div class="navbar-header">#}
{#                            <button class="navbar-toggle" data-target="#mobile_menu" data-toggle="collapse"><span#}
{#                                    class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>#}
{#                            </button>#}
{#                            <a href="#" class="navbar-brand">No Nonsense News</a>#}
{#                        </div>#}
{##}
{#                        <div class="navbar-collapse collapse" id="mobile_menu">#}
{#                            <ul class="nav navbar-nav">#}
{#                                <li class="active"><a href="{{ url_for('main.home_page') }}">Home</a></li>#}
{#                                <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">About Us <span class="caret"></span></a>#}
{#                                    <ul class="dropdown-menu">#}
{#                                        <li><a href="#">About One</a></li>#}
{#                                        <li><a href="#">About Two</a></li>#}
{#                                        <li><a href="#">About Three</a></li>#}
{#                                        <li><a href="#">About Four</a></li>#}
{#                                        <li><a href="#">About Five</a></li>#}
{#                                        <li><a href="#">About Six</a></li>#}
{#                                    </ul>#}
{#                                </li>#}
{#                                <li><a href="#">About us</a></li>#}
{#                                <li><a href="#">Welcome</a></li>#}
{#                                <li><a href="#">Services</a></li>#}
{#                                <li><a href="#">Contact Us</a></li>#}
{#                            </ul>#}
{#                            <ul class="nav navbar-nav">#}
{#                                <li>#}
{#                                    <form action="" class="navbar-form">#}
{#                                        <div class="form-group">#}
{#                                            <div class="input-group">#}
{#                                                <input type="search" name="search" id=""#}
{#                                                       placeholder="Search Anything Here..." class="form-control">#}
{#                                                <span class="input-group-addon"><span#}
{#                                                        class="glyphicon glyphicon-search"></span></span>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </form>#}
{#                                </li>#}
{#                            </ul>#}
{##}
{#                            <ul class="nav navbar-nav navbar-right">#}
{#                                {% if current_user.is_authenticated %}#}
{#                                    <li><a href="{{ url_for('users.profile_page',user_id=current_user.id) }}"><span#}
{#                                            class="glyphicon glyphicon-user"></span> Profile</a></li>#}
{#                                    <li><a href="{{ url_for('users.logout') }}"><span#}
{#                                            class="glyphicon glyphicon-log-out"></span>Logout</a></li>#}
{#                                {% else %}#}
{#                                    <li><a href="#" class="dropdown-toggle" data-toggle="dropdown"><span#}
{#                                            class="glyphicon glyphicon-log-in"></span> Login / Sign Up <span#}
{#                                            class="caret"></span></a>#}
{#                                        <ul class="dropdown-menu">#}
{#                                            <li><a href="{{ url_for('users.login_page') }}">Login</a></li>#}
{#                                            <li><a href="{{ url_for('users.registration_page') }}">Sign Up</a></li>#}
{#                                        </ul>#}
{#                                    </li>#}
{#                                {% endif %}#}
{#                            </ul>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    <!-- Bootstrap CSS -->#}
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"#}
{#          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">#}
{##}
{#<body>#}
{##}
{#<div class="row">#}
{#    <div class="col-md-12">#}
{#        {% with messages = get_flashed_messages(with_categories=true) %}#}
{#            {% if messages %}#}
{#                {% for category, message in messages %}#}
{#                    <div class="alert alert-{{ category }}">#}
{#                        {{ message }}#}
{#                    </div>#}
{#                {% endfor %}#}
{#            {% endif %}#}
{#        {% endwith %}#}
{#        {% block content %}{% endblock %}#}
{#    </div>#}
{#</div>#}
{##}
{##}
{#<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->#}
{#<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"#}
{#        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"#}
{#        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"#}
{#        crossorigin="anonymous"></script>#}
{#</body>#}
{#</html>#}
{##}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">No Nonsense News</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home_page') }}">Home</a>
                    <a class="nav-item nav-link" href="#">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link"
                           href="{{ url_for('users.profile_page', user_id=current_user.id) }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login_page') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.registration_page') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

news_website/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="content-section">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Log In</legend>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }}
                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-check">
                            {{ form.remember(class="form-check-input") }}
                            {{ form.remember.label(class="form-check-label") }}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                        <small class="text-muted ml-2">
                            <a href="{{ url_for('users.reset_password_request') }}">Forgot Password?</a>
                        </small>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Need An Account? <a class="ml-2" href="{{ url_for('users.registration_page') }}">Sign Up Now</a>
                    </small>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>

    </div>

{% endblock content %}

news_website/templates/post_article.html
{% extends layout.html %}
{% block content %}
<h3><a href="#">Post News</a></h3>
{% endblock content %}

news_website/templates/profile.html
{% extends 'layout.html' %}
{% block content %}
    <div> You are a {{ typeOfUser.type }}</div>
    <div> Hi {{ current_user.fname }} {{ current_user.lname }} </div>
{% endblock content %}

news_website/templates/registration.html
{% extends 'layout.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="container">
                <div class="content-section">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Join Today</legend>
                            <div>
                                {{ form.user_type.label(class="form-control-label") }}
                                {% for subfield in form.user_type %}
                                    <tr>
                                        <br>
                                        <td>{{ subfield(required=required) }}</td>
                                        <td>{{ subfield.label }}</td>
                                    </tr>
                                {% endfor %}
                            </div>
                            <div class="form-group">
                                {{ form.fname.label(class="form-control-label") }}

                                {% if form.fname.errors %}
                                    {{ form.fname(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.fname.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.fname(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.lname.label(class="form-control-label") }}

                                {% if form.lname.errors %}
                                    {{ form.lname(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.lname.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.lname(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div>
                                {{ form.gender.label(class="form-control-label") }}
                                {% for subfield in form.gender %}
                                    <tr>
                                        <br>
                                        <td>{{ subfield(required=required) }}</td>
                                        <td>{{ subfield.label }}</td>
                                    </tr>
                                {% endfor %}
                            </div>
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}
                                {% if form.email.errors %}
                                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.email(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.phone.label(class="form-control-label") }}
                                {% if form.phone.errors %}
                                    {{ form.phone(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.phone.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.phone(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.age.label(class="form-control-label") }}
                                {% if form.age.errors %}
                                    {{ form.age(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.age.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.age(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.address.label(class="form-control-label") }}
                                {% if form.address.errors %}
                                    {{ form.address(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.address.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.address(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.password.label(class="form-control-label") }}
                                {% if form.password.errors %}
                                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.password(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.confirm_password.label(class="form-control-label") }}
                                {% if form.confirm_password.errors %}
                                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.confirm_password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.confirm_password(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            {% block extraform %}{% endblock extraform %}
                        </fieldset>
                        <div class="form-group">

                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>

                    </form>
                    <div class="border-top pt-3">
                        <small class="text-muted">
                            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login_page') }}">Sign
                            In</a>
                        </small>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock content %}

news_website/templates/reset_password_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                           </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

news_website/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}